package lexer;

public enum TokenType {
  VAR, FUNC, IF, ELSE, RETURN,

  IDENTIFIER, NUMBER, STRING,

  PLUS, MINUS, MULT, DIV, MOD, ASSIGN,

  LE, GE, LT, GT, EQ, NE,

  SEMICOLON, COMMA, LPAREN, RPAREN, LBRACE, RBRACE,

  EOF
};
